[package]
name = "webb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
futures = "0.3.28"
hyper = { version = "0.14.25", features = ["server", "runtime"] }
lazy_static = "1.4.0"
open = "4.0.1"
rfesi = "0.15.0"
rusqlite = { version = "0.28.0", features = ["bundled-sqlcipher", "backup", "blob", "sqlcipher"] }
serde = { version = "1.0.159", features = ["derive"] }
tokio = { version = "1.27.0", features = ["tokio-macros", "rt", "rt-multi-thread", "macros"] }
uuid = { version = "1.3.0", features = ["v4", "v5", "wasm-bindgen"] }
